name: Test
on:
  pull_request: {}
  push:
    branches:
    - main
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Go 1.17
      uses: actions/setup-go@v3
      with:
        go-version: 1.17.6
      id: go
    - name: Lint
      run: make lint
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Go 1.17
      uses: actions/setup-go@v3
      with:
        go-version: 1.17.6
      id: go
    - name: Test
      run: make test
